package jimlind.filmlinkd.system.letterboxd.model;

// https://api-docs.letterboxd.com/#/schemas/ContributionType
public enum LbContributionType {
  Director,
  CoDirector,
  Actor,
  Producer,
  Writer,
  OriginalWriter,
  Story,
  Casting,
  Editor,
  Cinematography,
  AssistantDirector,
  AdditionalDirecting,
  ExecutiveProducer,
  Lighting,
  CameraOperator,
  AdditionalPhotography,
  ProductionDesign,
  ArtDirection,
  SetDecoration,
  SpecialEffects,
  VisualEffects,
  TitleDesign,
  Stunts,
  Choreography,
  Composer,
  Songs,
  Sound,
  Costumes,
  MakeUp,
  Hairstyling,
  Studio,
}
