options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "ghcr.io/opentofu/opentofu:latest"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd infra/compute
        tofu init
        tofu state rm module.compute.google_compute_instance.bot-vm
        tofu state rm module.compute.google_compute_instance.scraper-vm
        tofu destroy -auto-approve
        tofu apply -auto-approve

  - name: "ghcr.io/opentofu/opentofu:latest"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd infra/data
        tofu init
        tofu apply -auto-approve
    allowFailure: true