name: Build for GitHub Container Registry)

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image with Jib
        run: |
          mvn compile com.google.cloud.tools:jib-maven-plugin:build \
            -Dimage=ghcr.io/${{ github.repository }}:${{ github.sha }}