name: Build for GitHub Container Registry

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Git Tags
        id: tags
        run: |
          git fetch --tags
          GIT_TAGS=$(git tag --points-at HEAD | paste -sd, -)
          TAGS="${{ github.sha }},latest"
          if [ -n "${GIT_TAGS}" ]; then
            TAGS="${TAGS},${GIT_TAGS}"
          fi
          echo "TAGS=${TAGS}" >> $GITHUB_OUTPUT

      - name: Build and push container image with Jib
        run: |
          mvn compile com.google.cloud.tools:jib-maven-plugin:build \
            -Djib.to.image=ghcr.io/${{ github.repository }} \
            -Djib.to.tags=${{ steps.tags.outputs.TAGS }}