name: Run Maven Release
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package --no-transfer-progress

      - name: Prepare Release Artifacts
        run: |
          mkdir -p /tmp/release
          cp target/admin.jar target/bot.jar target/scraper.jar /tmp/release/
          cp docs/release/README.md /tmp/release/

      - name: Create GitHub Release and Upload Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${GITHUB_REF##*/}" /tmp/release/* --notes-file /tmp/release/README.md